// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjtfqsigglliafzhjhsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqdGZxc2lnZ2xsaWFmemhqaHNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTM1MDIsImV4cCI6MjA3MDY2OTUwMn0.QjSkNlehs5eZkN5TIH0jpsyyAr2ALjdtRD-LDEmfys8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});